Traceback (most recent call last):
  File "run.py", line 4, in <module>
    app.run(host='0.0.0.0', debug=True)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 717, in run_simple
    s.bind((hostname, port))
OSError: [Errno 98] Address already in use
